# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: io.github.carlossc87
description: >
  Sitio de mis proyectos y artículos sobre desarrollos y tecnología.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carlossc87.github.io" # the base hostname & protocol for your site
github_username:  carlossc87
linkedin_username: carlossc87
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
