# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog de proyectos de carlossc87
email: carlossc87@gmail.com
description: > 
  Blog sobre todos mis proyectos de desarrollo.
baseurl: ""
url: "http://carlossc87.github.io" # the base hostname & protocol for your site
github_username: carlossc87

# Build settings
markdown: kramdown
